[general]
import = ["~/.config/alacritty/colors.toml"]
live_config_reload = true
working_directory = "None"

[terminal.shell]
program = "/usr/bin/fish"
args = ["-l"]

[env]
TERM = "alacritty"

[window]
opacity = 0.92
blur = true
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "none"
dynamic_title = true
title = "alacritty"

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 20000
multiplier = 3

[font]
size = 11.0
offset = { x = 0, y = 0 }

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 600
unfocused_hollow = true
thickness = 0.18

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
duration = 100
color = "#F38BA8"

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

